# docker-compose 버전 정의
version: '3.2'

# 서비스 등록
services:
    client:
        restart: always

        # npm start: 실행 명령어
        command: npm start
        container_name: front
        build:
            context: ./client/
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        stdin_open: true
